openapi: 3.0.0
info:
  title: News Provider API
  description: This is a News Provider OpenAPI Specification for an API.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /News:
    get:
      operationId: getAllNews
      summary: Get all News
      description: Returns a list of all News.
      responses:
        '200':
          description: A list of News.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'

  /News/{id}:
    get:
      operationId: getSingleNews
      summary: Get a single News Entry
      description: Returns a single news entry
      parameters:
        - name: id
          in: path
          description: ID of the news entry to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single News entry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'

components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The news's ID.
        title:
          type: string
          description: The news's title.
        date:
          type: string
          description: The news's date.
        text:
          type: string
          description: The news's text.
        author:
          type: string
          description: The news's author.
